{% set name = "mesmerize-core" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nel-lab/mesmerize-core/archive/v{{ version }}.tar.gz
  sha256: 993d03433d463df29a37436b59d839288868037378deab5cd85a4116fa4d0429

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - caiman >=1.9.10
    - pandas >=1.5.0
    - requests
    - pytest
    - tqdm
    - numpy
    - matplotlib-base
    - click
    - psutil
    - jupyterlab

test:
  imports:
    - mesmerize_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nel-lab/mesmerize-core
  summary: High level pandas-based API for batch analysis of Calcium Imaging data using CaImAn
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kushalkolar
